# Generated by Django 3.2 on 2022-03-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='nirajmedia/projects'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=models.ImageField(upload_to='nirajmedia/skills'),
        ),
    ]
